### ISSUE TITLE
Dodać przykładowe dane seriali w liquibase

### ISSUE THREAD

**Issue by kp-marczynski** [kp-marczynski/seriesapp#11]

**Comment by kp-marczynski** [comment]
Branch nazwać PO-<nr zadania>, czyli PO-11.
Po ukończeniu przepisać mi na review

**Comment by MarutanF** [comment]
najlepiej w strukturze typu

Sherlock
-dane o serialu
-dane o odcinkach
-użytkownicy go obserwujący

użytkownicy którzy pooglądali odcinki

**Comment by kp-marczynski** [comment]
- [ ] dodać kilku użytkowników, dla każdego kilka ocenionych seriali i odcinków, żeby móc potem obliczyć średnią ocenę
- [ ] dodać ok 10-15 seriali
- [ ] dla każdego serialu dodać 2-8 sezonów
- [ ]  dla każdego sezonu dodać 1-10 odcinków
- [ ] powinien być przynajmniej jeden użytkownik który ma ocenione i skomentowane przynajmniej po 10 seriali/odcinków

**Comment by MarutanF** [comment]
Dodawanie użytkowników

Mam ich jakoś dodawać przez liquibase? Jeśli tak to czy wystarczy login i password_hash, w takim razie jaka funkcja może mi tam zahashować hasło?
Dodawanie przez intrfejs(user managment) nie pozwala ustawić hasła, tylko wymaga zrobienia tego przez emaila, a bez hasla nie można się zalogować.
