### ISSUE TITLE
Zle dodawanie lub wyswietlanie na front-endzie

### ISSUE THREAD

**Issue by MarutanF** [kp-marczynski/seriesapp#16]
Jak próbuję dodać FollowedSeries przez interfejs to:
- zmienia id usera zawsze na 3
- zamiast pokazywać ze nie może dodać tej samej pary to {user_id, series_id} to ja nadpisuje - jak dodam dane do FollowedSeries przez H2 to prawidłowo się wyświetlają (i wtedy też działa ograniczenie unique)

![zrzut ekranu 2018-12-08 16 09 11](https://user-images.githubusercontent.com/26172029/49687498-c9910c00-fb03-11e8-9b29-18225ec6c5c5.png)
![zrzut ekranu 2018-12-08 16 09 08](https://user-images.githubusercontent.com/26172029/49687499-c9910c00-fb03-11e8-9c2f-2ea4d53d764d.png)

**Comment by kp-marczynski** [comment]
tak, wiem, ale jest to nieistotne, bo nie będzie wgl tego widoku. oznaczanie obejrzanego odcinka będzie z poziomu odcinka i już napisałem część logiki do obsługi tego

**Comment by kp-marczynski** [comment]
teraaz na frontendzie automatycznie przypisuje zalogowanego użytkownika do dodania nowego obejrzanego odcinka, nawet jeśli użytkownik spróbuje dodać innego użytkownika
